// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX7tOkpi5ML1u0wiP-k5EA-_4TlRvcbdE',
    appId: '1:1051418951908:web:9d4cd9e5843d3cac642cf1',
    messagingSenderId: '1051418951908',
    projectId: 'fitnesstrackapp-a0b67',
    authDomain: 'fitnesstrackapp-a0b67.firebaseapp.com',
    storageBucket: 'fitnesstrackapp-a0b67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJYCmak5m_YBbY0TsxdIldLaDJUyLkr4',
    appId: '1:1051418951908:android:f0a0a03dadef851b642cf1',
    messagingSenderId: '1051418951908',
    projectId: 'fitnesstrackapp-a0b67',
    storageBucket: 'fitnesstrackapp-a0b67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB38oK9Jp8IUN75F-P8_yw2D1WHZkr6HK8',
    appId: '1:1051418951908:ios:6917d7002a54c51e642cf1',
    messagingSenderId: '1051418951908',
    projectId: 'fitnesstrackapp-a0b67',
    storageBucket: 'fitnesstrackapp-a0b67.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB38oK9Jp8IUN75F-P8_yw2D1WHZkr6HK8',
    appId: '1:1051418951908:ios:6917d7002a54c51e642cf1',
    messagingSenderId: '1051418951908',
    projectId: 'fitnesstrackapp-a0b67',
    storageBucket: 'fitnesstrackapp-a0b67.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX7tOkpi5ML1u0wiP-k5EA-_4TlRvcbdE',
    appId: '1:1051418951908:web:2827bf547408b9e6642cf1',
    messagingSenderId: '1051418951908',
    projectId: 'fitnesstrackapp-a0b67',
    authDomain: 'fitnesstrackapp-a0b67.firebaseapp.com',
    storageBucket: 'fitnesstrackapp-a0b67.firebasestorage.app',
  );
}
