name: fitness_tracker_app
description: "A new Flutter project."

# Prevent accidental publish to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  percent_indicator: ^4.2.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  csv: ^6.0.0
  pdf: ^3.11.0
  printing: ^5.12.0
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Fitness.json
    - assets/steps.json
    - assets/workout.json
    - assets/calories.json
    - assets/login.json
    - assets/signup.json
   
